"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import {
  ChevronRight,
  ChevronLeft,
  X,
  ShieldCheck,
  Target,
  FileCheck,
  AlertCircle,
  RefreshCw,
  ExternalLink,
  Check,
} from "lucide-react";
import { cn } from "@/lib/utils";

interface TourStep {
  title: string;
  badge: string;
  href: string;
  icon: React.ElementType;
  pitch: string;
  keyHighlights: string[];
  recommendedAction: string;
}

const TOUR_STEPS: TourStep[] = [
  {
    title: "1. The Financial Reconciliation Problem",
    badge: "01 · Scale & Variance",
    href: "/sandbox",
    icon: AlertCircle,
    pitch: "Modern digital commerce processes millions of multi-channel transactions daily across gateways, banks, and ledgers. Manual spreadsheet triage causes fee leakage, delayed dispute resolutions, and balance drift.",
    keyHighlights: [
      "Fragmented data across order carts, payment gateways, and bank settlement feeds",
      "Gateway fee discrepancies, MDR rate shifts, and partial refund mismatches",
      "Manual reconciliation bottlenecks that delay month-end financial closing",
      "High operational risk when LLMs are mistakenly given direct database write access",
    ],
    recommendedAction: "Inspect raw multi-party transaction batches in the Interactive Sandbox.",
  },
  {
    title: "2. Deterministic Reconciliation First",
    badge: "02 · Rule-Engine Core",
    href: "/judge-mode",
    icon: Target,
    pitch: "The financial source of truth is governed by deterministic rules, exact integer-paise arithmetic, and UTR matching. Over 96% of transactions resolve instantly without invoking any AI model.",
    keyHighlights: [
      "3-pass multi-window reconciliation: Exact UTR, Order ID + Amount, and Sliding Window",
      "Exact integer paise math: Zero floating-point drift (Debits == Credits guaranteed)",
      "98.1% accuracy, 98% precision, and 98% recall on the official benchmark dataset",
      "High throughput: >900 records/sec per single CPU core on local execution",
    ],
    recommendedAction: "Execute the benchmark evaluation in Judge Mode.",
  },
  {
    title: "3. Honest Exception Detection",
    badge: "03 · Variance Isolation",
    href: "/exceptions",
    icon: AlertCircle,
    pitch: "When financial variances occur, SettleMate isolates them with structured reason codes, exact paise shortfall deltas, and immutable Context Vault evidence links.",
    keyHighlights: [
      "Clear taxonomy: Fee overcharges, partial refunds, delayed settlements, duplicate credits",
      "Side-by-side expected vs. actual breakdown with exact delta calculation",
      "Context Vault evidence links referencing source vouchers and bank statements",
      "Dual-control Maker/Checker authorization required before journal entry posting",
    ],
    recommendedAction: "Triage pending exceptions in the Exception Workbench.",
  },
  {
    title: "4. AI Investigation (Advisory-Only)",
    badge: "04 · AI Root Cause",
    href: "/chat",
    icon: ShieldCheck,
    pitch: "AI assists operations by analyzing discrepancies, identifying fee anomalies, and proposing resolutions, but is strictly advisory. The AI cannot mutate database records or execute financial transfers.",
    keyHighlights: [
      "Powered by Google Gemini for natural-language anomaly root-cause investigation",
      "Emits structured, auditable hypothesis claims referencing explicit evidence IDs",
      "Clear visual indicators for 'Live Gemini' vs 'Offline Fallback' mode",
      "Zero secret leakage: API keys and sensitive customer PII are redacted from prompts",
    ],
    recommendedAction: "Ask questions in Finance Q&A to investigate exception root causes.",
  },
  {
    title: "5. Non-LLM Claim Validation",
    badge: "05 · Safety Boundary",
    href: "/security",
    icon: ShieldCheck,
    pitch: "Every claim generated by an LLM is mechanically validated against raw transaction feeds by a non-LLM rule engine operating at 134,511 claims/sec before human authorization.",
    keyHighlights: [
      "AI output is treated as untrusted input and subjected to deterministic proof rules",
      "Arithmetic verification: Claimed amount must equal the exact paise voucher balance",
      "Evidence existence check: Cited voucher or UTR must exist in the immutable vault",
      "Mathematically impossible for hallucinated AI output to enter the financial ledger",
    ],
    recommendedAction: "Review the Non-LLM Validation Gates in the Self-Test & Hardening Hub.",
  },
  {
    title: "6. Adversarial Defense & Hostile Input Lab",
    badge: "06 · Red Team Defense",
    href: "/red-team",
    icon: RefreshCw,
    pitch: "Tested against hostile prompt injections, fake voucher IDs, SSRF payloads, and corrupted bank narrations with an official 90% adversarial catch rate.",
    keyHighlights: [
      "10 distinct attack vectors tested continuously in the Red Team Defense lab",
      "SSRF guard blocks attempts to query AWS/GCP metadata (169.254.169.254) and loopback",
      "Prompt injection payloads trying to override balance checks are blocked in <10ms",
      "Financial conservation invariant is preserved under all hostile conditions",
    ],
    recommendedAction: "Simulate hostile prompt injections in the Red Team Defense lab.",
  },
  {
    title: "7. Cryptographic Decision Receipts",
    badge: "07 · Merkle DAG Audit",
    href: "/audit-trail",
    icon: FileCheck,
    pitch: "Every finalized reconciliation outcome emits a self-contained Decision Receipt sealed with a SHA-256 Merkle DAG root that external auditors can verify in <1ms without calling any LLM.",
    keyHighlights: [
      "Self-contained Merkle DAG links transaction inputs, validator proofs, and approvals",
      "Standalone in-browser offline verifier (0 external dependencies, 0 LLM calls)",
      "Instant bitwise detection of any tampered ledger amounts or modified hashes",
      "Exportable compliance bundles for statutory auditing and regulatory reporting",
    ],
    recommendedAction: "Verify an offline decision receipt in the General Ledger & DAG view.",
  },
  {
    title: "8. Operational & Developer Integration",
    badge: "08 · Enterprise API",
    href: "/developer",
    icon: FileCheck,
    pitch: "Engineered for seamless enterprise integration with OpenAPI 3.1 REST endpoints, real-time Server-Sent Events (SSE) telemetry, and transactional webhook delivery with AES-256 encryption.",
    keyHighlights: [
      "Complete v1 REST API (`/api/v1/reconcile`, `/api/v1/stream/events`, `/api/v1/ready`)",
      "Real-time SSE event streaming with stateless PostgreSQL replay on client reconnect",
      "Transactional webhook outbox with HMAC-SHA256 signing, exponential backoff, and DLQ",
      "Distributed multi-tier sliding-window rate limiting with graceful local fallback",
    ],
    recommendedAction: "Explore OpenAPI specs, test webhooks, and generate API keys in Developer Portal.",
  },
];

export function GuidedTourModal({
  isOpen,
  onClose,
}: {
  isOpen: boolean;
  onClose: () => void;
}) {
  const [currentStep, setCurrentStep] = useState<number>(0);

  // Keyboard navigation & Escape
  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if (!isOpen) return;
      if (e.key === "Escape") {
        onClose();
      } else if (e.key === "ArrowRight") {
        setCurrentStep((prev) => Math.min(prev + 1, TOUR_STEPS.length - 1));
      } else if (e.key === "ArrowLeft") {
        setCurrentStep((prev) => Math.max(prev - 1, 0));
      }
    }
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  const step = TOUR_STEPS[currentStep];
  const isFirst = currentStep === 0;
  const isLast = currentStep === TOUR_STEPS.length - 1;

  const handleNext = () => {
    if (!isLast) {
      setCurrentStep((prev) => prev + 1);
    } else {
      onClose();
    }
  };

  const handlePrev = () => {
    if (!isFirst) {
      setCurrentStep((prev) => prev - 1);
    }
  };

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="tour-dialog-title"
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-xs animate-in fade-in-0 duration-100"
    >
      <div
        className="fixed inset-0"
        onClick={onClose}
      />

      <div className="relative z-50 w-full max-w-2xl rounded-xl border border-border bg-popover text-popover-foreground shadow-2xl overflow-hidden font-sans">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-border px-6 py-4">
          <div>
            <div className="text-xs text-muted-foreground font-medium">
              Product Tour · Step {currentStep + 1} of {TOUR_STEPS.length}
            </div>
            <h2 id="tour-dialog-title" className="text-lg font-semibold text-foreground tracking-tight">
              {step.title}
            </h2>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="p-1.5 text-muted-foreground hover:text-foreground transition-colors"
            aria-label="Close tour"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Step Indicator */}
        <div className="grid grid-cols-8 gap-1.5 bg-muted/40 p-1.5 border-b border-border">
          {TOUR_STEPS.map((s, idx) => (
            <button
              key={s.badge}
              type="button"
              onClick={() => setCurrentStep(idx)}
              className={cn(
                "h-1.5 rounded-full transition-all",
                idx === currentStep
                  ? "bg-primary"
                  : idx < currentStep
                  ? "bg-primary/40"
                  : "bg-muted"
              )}
              title={s.title}
            />
          ))}
        </div>

        {/* Body */}
        <div className="p-6 space-y-5">
          <p className="text-sm leading-relaxed text-muted-foreground">
            {step.pitch}
          </p>

          {/* Highlights */}
          <div className="rounded-lg border border-border bg-card p-4 space-y-2">
            <div className="text-xs text-muted-foreground font-medium">
              Key Proof Points
            </div>
            <div className="space-y-2">
              {step.keyHighlights.map((h) => (
                <div key={h} className="flex items-start gap-2.5 text-sm text-foreground">
                  <Check className="h-4 w-4 text-emerald-500 shrink-0 mt-0.5" />
                  <span>{h}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Action Link */}
          <div className="flex items-center justify-between gap-4 rounded-lg border border-border bg-card p-3 text-sm">
            <span className="text-muted-foreground text-xs sm:text-sm">
              <strong className="text-foreground">Action:</strong> {step.recommendedAction}
            </span>
            <Link
              href={step.href}
              onClick={onClose}
              className="inline-flex items-center gap-1.5 text-xs sm:text-sm font-medium text-foreground hover:underline shrink-0"
            >
              <span>View live</span>
              <ExternalLink className="h-3.5 w-3.5" />
            </Link>
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between border-t border-border px-6 py-3.5 bg-card/50">
          <button
            type="button"
            onClick={handlePrev}
            disabled={isFirst}
            className="inline-flex h-8 items-center gap-1.5 rounded-lg border border-border bg-secondary px-3 text-xs font-medium text-secondary-foreground hover:bg-secondary/80 disabled:opacity-30 disabled:pointer-events-none transition"
          >
            <ChevronLeft className="h-3.5 w-3.5" />
            <span>Previous</span>
          </button>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={onClose}
              className="h-8 rounded-lg px-3 text-xs text-muted-foreground hover:text-foreground transition"
            >
              Skip
            </button>

            <button
              type="button"
              onClick={handleNext}
              className="inline-flex h-8 items-center gap-1.5 rounded-lg bg-primary px-3.5 text-xs font-medium text-primary-foreground hover:bg-primary/90 transition"
            >
              <span>{isLast ? "Done" : "Next"}</span>
              <ChevronRight className="h-3.5 w-3.5" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
