-- =========================================================================
-- SettleMate AI — Durable Domain Event Store + Batch.amountAtRisk widening
-- =========================================================================
--
-- Two defects are corrected here.
--
-- 1. `DomainEvent` is declared in prisma/schema.postgresql.prisma and written to
--    by UnifiedDomainEventRepository, but no migration ever created the table.
--    Every durable event write therefore failed against a migrated production
--    database, and the SSE Last-Event-ID replay path had nothing to read.
--
--    `seq` is a database-assigned identity column. The application must not
--    supply it: a process-local counter restarts at 1 on every deploy and is
--    independent per instance, which collides with @@unique("tenantId","seq").
--
-- 2. `Batch.amountAtRisk` stores a sum of exception amounts in paise but was
--    INTEGER, so any batch with more than ~₹2.14 crore at risk failed to
--    persist with "integer out of range". This is the same overflow class as
--    BankTransaction.balance, widened in 20260830.
--
-- Every statement is guarded so the migration is safe to re-run and safe to
-- apply to a database that was partially migrated.

-- -------------------------------------------------------------------------
-- 1. Durable domain event store
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "DomainEvent" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL DEFAULT 'tenant_default_sandbox',
    "eventType" TEXT NOT NULL,
    "entityId" TEXT NOT NULL,
    "seq" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "traceId" TEXT,
    "payload" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "DomainEvent_pkey" PRIMARY KEY ("id")
);

DO $$
BEGIN
    ALTER TABLE "DomainEvent"
        ADD CONSTRAINT "DomainEvent_tenantId_fkey"
        FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id")
        ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN
    -- Constraint already present
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "DomainEvent_tenantId_seq_key" ON "DomainEvent"("tenantId", "seq");
CREATE INDEX IF NOT EXISTS "DomainEvent_tenantId_entityId_idx" ON "DomainEvent"("tenantId", "entityId");
CREATE INDEX IF NOT EXISTS "DomainEvent_createdAt_idx" ON "DomainEvent"("createdAt");
CREATE INDEX IF NOT EXISTS "DomainEvent_tenantId_idx" ON "DomainEvent"("tenantId");

-- Row-Level Security, matching the policy installed by 20260829_tenant_rls.
ALTER TABLE "DomainEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DomainEvent" FORCE ROW LEVEL SECURITY;

DO $$
BEGIN
    EXECUTE 'CREATE POLICY tenant_isolation_policy ON "DomainEvent" FOR ALL USING ("tenantId" = CURRENT_SETTING(''app.current_tenant_id'', true)) WITH CHECK ("tenantId" = CURRENT_SETTING(''app.current_tenant_id'', true));';
EXCEPTION WHEN duplicate_object THEN
    -- Policy already present
END $$;

-- -------------------------------------------------------------------------
-- 2. Widen Batch.amountAtRisk to BIGINT (paise aggregate)
-- -------------------------------------------------------------------------
ALTER TABLE "Batch" ALTER COLUMN "amountAtRisk" TYPE BIGINT;

-- -------------------------------------------------------------------------
-- 3. Essential tenant-isolation and query indexes for operational tables
-- -------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS "DecisionReceipt_tenantId_createdAt_idx" ON "DecisionReceipt"("tenantId", "createdAt");
CREATE INDEX IF NOT EXISTS "DecisionReceipt_tenantId_fingerprint_idx" ON "DecisionReceipt"("tenantId", "fingerprint");
CREATE INDEX IF NOT EXISTS "AiClaimLog_tenantId_exceptionId_idx" ON "AiClaimLog"("tenantId", "exceptionId");
CREATE INDEX IF NOT EXISTS "WebhookSubscription_tenantId_status_idx" ON "WebhookSubscription"("tenantId", "status");
CREATE INDEX IF NOT EXISTS "WebhookOutbox_tenantId_status_idx" ON "WebhookOutbox"("tenantId", "status");
CREATE INDEX IF NOT EXISTS "WebhookOutbox_status_nextAttemptAt_idx" ON "WebhookOutbox"("status", "nextAttemptAt");
CREATE INDEX IF NOT EXISTS "AsyncJob_tenantId_status_idx" ON "AsyncJob"("tenantId", "status");
CREATE INDEX IF NOT EXISTS "AsyncJob_status_leaseExpiresAt_idx" ON "AsyncJob"("status", "leaseExpiresAt");
